blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:post_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('dothisbird/', include('todo.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.home, name='home'),

    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),

    # Todos
    path('todos/', views.todos, name='todos'),
    path('completedtodos/', views.completedtodos, name='completedtodos'),
    path('todo/<int:todo_pk>', views.viewtodo, name='viewtodo'),
    path('create/', views.createtodo, name='createtodo'),
    path('todo/<int:todo_pk>/complete', views.completetodo, name='completetodo'),
    path('todo/<int:todo_pk>/delete', views.deletetodo, name='deletetodo'),
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.title
        

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class ToDo(models.Model):
    # Content of the todo
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)

    # Created at
    created_at = models.DateTimeField(auto_now_add=True)

    # User who owns this todo
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Urgency of this todo
    urgent = models.BooleanField(default=False)

    # Completed boolean
    completed = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm
from .models import ToDo

class TodoForm(ModelForm):
    class Meta:
        model = ToDo
        fields = ['title', 'memo', 'urgent']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def all_blogs(request):
    posts = Post.objects.order_by('-created')
    return render(request, 'blog/all_blogs.html', {'posts': posts})

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/detail.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import TodoForm
from .models import ToDo

# Home
def home(request):
    return render(request, 'todo/home.html')

# Auth
def signupuser(request):
    if request.method == 'POST':
        # Check if user exists, return error if yes
        # Check is passwords match
        if request.POST['password1'] == request.POST['password2']:
            # Create a new user
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('todo:todos')
            except IntegrityError:
                return render(request, 'todo/signupuser.html', {'form': UserCreationForm(), 'error': 'That username is already taken. Please choose another username.'})
        else:
            # Return password mismatch error
            print("Password mismatch error")
            return render(request, 'todo/signupuser.html', {'form': UserCreationForm(), 'error': 'Password mismatch'})

    else:
        return render(request, 'todo/signupuser.html', {'form': UserCreationForm()})

def loginuser(request):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'todo/loginuser.html', {'form': AuthenticationForm(), 'error': 'Unable to log in. Please try again.'})
        else:
            login(request, user)
            return redirect('todo:todos')

    else:
        return render(request, 'todo/loginuser.html', {'form': AuthenticationForm()})

@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('todo:home')


# Todo
@login_required
def todos(request):
    todos = ToDo.objects.filter(user=request.user, completed__isnull=True)
    return render(request, 'todo/todos.html', {'todos': todos})

@login_required
def completedtodos(request):
    todos = ToDo.objects.filter(user=request.user, completed__isnull=False)
    return render(request, 'todo/completedtodos.html', {'todos': todos})

@login_required
def viewtodo(request, todo_pk):
    todo = get_object_or_404(ToDo, pk=todo_pk, user=request.user)
    
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        try:
            form.save()
        except ValueError:
            return render(request, 'todo/viewtodo.html', {'todo': todo, 'form': form, 'error': 'Bad info'})
        return redirect('todo:todos')
    else:
        form = TodoForm(instance=todo)
        return render(request, 'todo/viewtodo.html', {'todo': todo, 'form': form})

@login_required
def createtodo(request):
    if request.method == 'POST':
        try:
            form = TodoForm(request.POST)
            new_todo = form.save(commit=False)
            new_todo.user = request.user
            new_todo.save()
            return redirect('todo:todos')
        except ValueError:
            return render(request, 'todo/createtodo.html', {'form': TodoForm(), 'error': 'Bad data'})
    else:
        return render(request, 'todo/createtodo.html', {'form': TodoForm()})

@login_required
def completetodo(request, todo_pk):
    todo = get_object_or_404(ToDo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.completed = timezone.now()
        todo.save()
        return redirect('todo:todos')

@login_required
def deletetodo(request, todo_pk):
    todo = get_object_or_404(ToDo, pk=todo_pk, user=request.user)
    if request.method == 'POST':
        try:
            todo.delete()
            return redirect('todo:todos')
        except:
            form = TodoForm(instance=todo)
            return render(request, 'todo/viewtodo.html', {'todo': todo, 'form': form, 'error': 'Error deleting todo'})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h2>Blogs</h2>
<p>Sparrow has written {{ posts.count }} blog post{{ posts.count|pluralize }}</p>
{% for post in posts %}
  <a href="{% url 'blog:detail' post.id %}"><h3>{{ post.title }}</h3></a>
  <h5>{{ post.created }}</h5>
  <p>{{ post.content|striptags|truncatechars:100 }}</p>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h2>{{ post.title }}</h2>
<pre>{{ post.created|date:"D M jS Y"|upper }}</pre>
<p>{{ post.content|safe }}</p>

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://use.fontawesome.com/658ae2afd2.js"></script>

    <link rel="stylesheet" href="{% static 'portfolio/styles.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">

    <title>A Sparrow Portfolio</title>
  </head>
  <body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">Alex Sparrow</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% static 'portfolio/resume.pdf' %}" target="_blank">Resume</a>
          </li>
        </ul>
      </div>
    </nav>

    <!-- Page content -->
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Social Media Icons -->
    <nav class="navbar navbar-expand-lg fixed-bottom navbar-dark bg-dark">
      <div class="container">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/ZanderSparrow" target="_blank"><i class="fa fa-github-alt" aria-hidden="true"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/zandersparrow/" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.instagram.com/zandersparrow/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
          </li>
        </ul>
      </div>
    </nav>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block content %}
<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/sparrow.jpg' %}" class="img-fluid portrait" alt="picture of me">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <p class="lead" id="hometext">Alex Sparrow is a Backend Developer and an Arist. They live in Berkeley, CA.</p>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>
    {% if project.url %}
      <a href="{{ project.url }}" ><img src="{{ project.image.url }}" class="img-fluid mb-2" alt="{{ project.title }} image" width="500"></a>
    {% else %}
      <img src="{{ project.image.url }}" class="img-fluid mb-2" alt="{{ project.title }} image" width="500">
    {% endif %}
  </div>
  {% endfor %}
</div>

{% endblock %}

todo/templates/todo/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'todo/styles.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&display=swap" rel="stylesheet">

    <title>Do This, Bird</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'todo/favicon.ico' %}"/>

  </head>
  <body>
    <!-- Nav bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'todo:home' %}">
        <img src="{% static 'todo/favicon-32x32.png' %}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
        Do This, Bird
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="navbar-brand dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Do Something
              
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'todo:todos' %}">Current Todos</a>
              <a class="dropdown-item" href="{% url 'todo:createtodo' %}">Create</a>
              <a class="dropdown-item" href="{% url 'todo:completedtodos' %}">Completed</a>
              <div class="dropdown-divider"></div>
              <span>Logged in as {{ user.username }}</span>
              <form class="form-inline text-center" action="{% url 'todo:logoutuser' %}" method=POST>
                {% csrf_token %}
          
                <button class="dropdown-item" type="submit">Logout</button>
              </form>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo:signupuser' %}">Signup</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo:loginuser' %}">Login</a>
          </li>
          {% endif %}
        </ul>
        
      </div>
    </nav>
    <!-- Site Content -->
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

todo/templates/todo/completedtodos.html
{% extends 'todo/base.html' %}

{% block content %}
<h2>Todos</h2>
<ul>
  {% for todo in todos %}
  <li>
    {% if todo.urgent %}<b>{% endif %}
      {{todo.title}}
    {% if todo.urgent %}</b>{% endif %}
    {% if todo.memo %}
      - {{todo.memo}}
    {% endif %}
    {{ completed }}
  </li>
  {% endfor %}
</ul>
{% endblock %}

todo/templates/todo/createtodo.html
{% extends 'todo/base.html' %}

{% block content %}
<h2>Create Todo</h2>

{% if error %}
<h3>{{ error }}</h3>
{% endif %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock %}

todo/templates/todo/home.html
{% extends 'todo/base.html' %}

{% block content %}
<br>
<h2>Welcome, you beautiful bird</h2>
<br>
<ul class="home-list">
  <li>This is a quiet place to keep a list</li>
  <li>A list about the future</li>
  <li>A list of things to remember</li>
  <li>Things to do</li>
  <li>And things already done</li>
</ul>

{% endblock %}

todo/templates/todo/loginuser.html
{% extends 'todo/base.html' %}

{% block content %}
<h2>Login</h2>

{% if error %}
<h3>{{ error }}</h3>
{% endif %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>
{% endblock %}

todo/templates/todo/signupuser.html
{% extends 'todo/base.html' %}

{% block content %}
<h2>Sign Up!</h2>

{% if error %}
<h3>{{ error }}</h3>
{% endif %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>
{% endblock %}

todo/templates/todo/todos.html
{% extends 'todo/base.html' %}

{% block content %}
<h2>Todos</h2>
<ul>
  {% for todo in todos %}
  <li>
    <a href="{% url 'todo:viewtodo' todo.id %}">
      {% if todo.urgent %}<b>{% endif %}
        {{todo.title}}
      {% if todo.urgent %}</b>{% endif %}
      {% if todo.memo %}
        - {{todo.memo}}
      {% endif %}
    </a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

todo/templates/todo/viewtodo.html
{% extends 'todo/base.html' %}

{% block content %}
<h2>{{todo.title}}</h2>

{{ error }}

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

<form method="POST" action="{% url 'todo:completetodo' todo.id %}">
  {% csrf_token %}
  <button type="submit">Complete</button>
</form>

<form method="POST" action="{% url 'todo:deletetodo' todo.id %}">
  {% csrf_token %}
  <button type="submit">Delete</button>
</form>

{% endblock %}